function latlongsamples = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LATLONGSAMPLES = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  LATLONGSAMPLES = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  latlongsamples = importfile("/Users/gadiraju.s13/Library/CloudStorage/OneDrive-JohnsHopkins/Documents/ASBR/Assignment 4/Matlab Files/latlong_samples.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Apr-2023 15:30:28

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 19);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "fieldheaderseq", "fieldheaderstamp", "Var4", "Var5", "Var6", "fieldlatitude", "fieldlongitude", "fieldaltitude", "fieldposition_covariance0", "fieldposition_covariance1", "fieldposition_covariance2", "fieldposition_covariance3", "fieldposition_covariance4", "fieldposition_covariance5", "fieldposition_covariance6", "fieldposition_covariance7", "Var18", "Var19"];
opts.SelectedVariableNames = ["time", "fieldheaderseq", "fieldheaderstamp", "fieldlatitude", "fieldlongitude", "fieldaltitude", "fieldposition_covariance0", "fieldposition_covariance1", "fieldposition_covariance2", "fieldposition_covariance3", "fieldposition_covariance4", "fieldposition_covariance5", "fieldposition_covariance6", "fieldposition_covariance7"];
opts.VariableTypes = ["double", "double", "double", "string", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var4", "Var5", "Var6", "Var18", "Var19"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var4", "Var5", "Var6", "Var18", "Var19"], "EmptyFieldRule", "auto");

% Import the data
latlongsamples = readtable(filename, opts);

%% Convert to output type
latlongsamples = table2array(latlongsamples);
end